sudo: false

language: erlang

otp_release:
  - 20.1

addons:
  apt:
    packages:
    - yasm

cache:
  directories:
  - $HOME/.cache/rebar3
  - $HOME/.cache/pbc

before_script:
    kerl list installations &&
    git clone https://github.com/blynn/pbc &&
    cd pbc &&
    autoreconf -fvi &&
    ./configure --prefix $HOME/.cache/pbc &&
    make &&
    make install &&
    cd ..

script: CFLAGS="-I $HOME/.cache/pbc/include" LDFLAGS="-L$HOME/.cache/pbc/lib" LD_LIBRARY_PATH="$HOME/.cache/pbc/lib" ./rebar3 as test do eunit,ct && ./rebar3 dialyzer && ./rebar3 coveralls send
